const styles = (theme) => ({
  eventOptionWrapper: {
    width: '100%',
    display: 'block',
    position: 'relative',
    paddingRight: '0 !important',
    marginTop: theme.padding.spaceX.px,
    marginBottom: theme.padding.spaceX.px,
    '&.noMargin': {
      margin: 0,
    },
    '&.last': {
      marginBottom: theme.padding.space2X.px,
    },
    '&:hover': {
      transform: 'scale(1.025)',
    },
  },
  overText: {
    textOverflow: 'ellipsis',
    overflow: 'hidden',
    whiteSpace: 'nowrap',
    lineHeight: '1.5',
    paddingLeft: theme.padding.space2X.px,
    color: '#fe0672',
    fontSize: '1.05rem',
    fontWeight: '400',
    fontFamily: 'Noto Sans TC, sans-serif',
  },
  eventOptionNum: {
    background: theme.palette.background.grey,
    height: theme.sizes.icon.large,
    width: theme.sizes.icon.large,
    lineHeight: theme.sizes.icon.large,
    borderRadius: theme.sizes.icon.large,
    overflow: 'hidden',
    textAlign: 'center',
    fontSize: theme.sizes.font.xxSmall,
    fontWeight: theme.typography.fontWeightBold,
    color: theme.palette.text.primary,
    position: 'absolute',
    left: 0,
    top: 0,
  },
  eventOptionIcon: {
    height: theme.sizes.icon.large,
    width: theme.sizes.icon.large,
    lineHeight: 1,
    fontSize: theme.sizes.icon.large,
    color: theme.palette.text.primary,
    position: 'absolute',
    left: 0,
    top: '-7px',
  },
  eventOptionProgress: {
    position: 'relative',
    marginTop: theme.padding.spaceX.px,
    marginBottom: theme.padding.spaceX.px,
    height: '50px',
  },
  eventOptionProgressNum: {
    lineHeight: 1.5,
    textAlign: 'right',
    height: '100%',
    paddingRight: theme.padding.spaceX.px,
    color: '#fe0672',
    fontSize: '1.05rem',
    fontWeight: '400',
    fontFamily: 'Noto Sans TC, sans-serif',
    whiteSpace: 'nowrap',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  eventOptionInput: {
    fontSize: theme.sizes.font.xLarge,
    height: '22px',
  },
  root: {
    height: '100%',
    boxShadow: '0 2px 10px rgba(0,0,0,.2) !important',
  },
  textWrapper: {
    width: '100%',
    height: 50,
    position: 'absolute',
    display: 'flex',
    justifyContent: 'space-between',
    zIndex: 100,
  },
});

export default styles;
