import antdEn from 'antd/lib/locale-provider/en_US';
import appLocaleData from 'react-intl/locale-data/en';
import enMessages from '../locales/en_US.json';

const EnLang = {
  messages: {
    'cornerclock.online': 'Online',
    'cornerclock.offline': 'Offline',
    'cornerclock.block': 'Current Block',
    'topbar.events': 'Events',
    'topbar.create': 'Create an Event',
    'dashboard.Bet': 'Bet',
    'dashboard.Set': 'Set',
    'dashboard.Vote': 'Vote',
    'dashboard.Finalize': 'Finalize',
    'dashboard.Withdraw': 'Withdraw',
    'sort.asc': 'Ascending',
    'sort.desc': 'Descending',
    'sort.default': 'Sort',
    'bottombutton.placebet': 'Place Bet',
    'bottombutton.setresult': 'Set Result',
    'bottombutton.vote': 'Place Vote',
    'bottombutton.final': 'Finalize Result',
    'bottombutton.withdraw': 'Withdraw',
    'create.title': 'Create an event',
    'create.name': 'Name',
    'create.betstartblock': 'BETTING START BLOCK',
    'create.betendblock': 'Betting End Block',
    'create.resultsetstartblock': 'Result Setting Start Block',
    'create.resultsetendblock': 'Result Setting End Block',
    'create.results': 'RESULTS',
    'create.resultsetter': '"Centralized Oracle"',
    'create.back': 'Back',
    'create.cancel': 'Cancel',
    'create.publish': 'Publish',
    'create.addresult': 'Add Result',
    'cardinfo.topic': 'Topic Created',
    'cardinfo.betting': 'Betting',
    'cardinfo.orresultset': 'Oracle Result Setting',
    'cardinfo.opresultset': 'Open Result Setting',
    'cardinfo.vote': 'Voting',
    'cardinfo.final': 'Finalizing',
    'cardinfo.block': 'Block',
    'cardinfo.withdraw': 'Withdrawal',
  },
  antd: antdEn,
  locale: 'en-US',
  data: appLocaleData,
};
export default EnLang;
