import antdZh from 'antd/lib/locale-provider/zh_TW';
import appLocaleData from 'react-intl/locale-data/zh';
import zhMessages from '../locales/zh-Hans.json';

const ZhLan = {
  messages: {
    'topbar.events': '事件',
    'topbar.create': '创建事件',
    'topbar.block': '当前区块数',
    'dashboard.Bet': '下注',
    'dashboard.Set': '设置',
    'dashboard.Vote': '投票',
    'dashboard.Finalize': '结束',
    'dashboard.Withdraw': '提现',
    'sort.asc': '升序',
    'sort.desc': '降序',
    'sort.default': '排序',
    'bottombutton.placebet': '下注',
    'bottombutton.setresult': '设置结果',
    'bottombutton.vote': '投票',
    'bottombutton.final': '最终设定',
    'bottombutton.withdraw': '提现',
    'create.title': '创建事件',
    'create.name': '名称',
    'create.betstartblock': '投注开始区块数',
    'create.betendblock': '投注结束区块数',
    'create.resultsetstartblock': '结果设置开始区块数',
    'create.resultsetendblock': '结果设置结束区块数',
    'create.results': '结果',
    'create.resultsetter': '结果设置人',
    'create.back': '返回',
    'create.cancel': '取消',
    'create.publish': '发布',
    'create.addresult': '添加结果',
    'cardinfo.topic': '项目创建',
    'cardinfo.betting': '下注',
    'cardinfo.orresultset': 'Oracle结果设定',
    'cardinfo.opresultset': '开放结果设定',
    'cardinfo.vote': '投票',
    'cardinfo.final': '结束',
    'cardinfo.block': '区块数',
    'cardinfo.withdraw': '取出',
  },
  antd: antdZh,
  locale: 'zh-Hans-CN',
  data: appLocaleData,
};
export default ZhLan;
